[package]
name = "sinter-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "sinter command-line interface"

[[bin]]
name = "sinter"
path = "src/main.rs"

[dependencies]
sinter-core.workspace = true
sinter-store.workspace = true
sinter-extract.workspace = true
sinter-resolve.workspace = true
clap.workspace = true
clap_complete.workspace = true
anyhow = "1"
rayon = "1"
ignore = "0.4"
notify = "8"
blake3 = "1"
serde.workspace = true
serde_json = "1"
libc = "0.2"
toml = "0.8"
redb.workspace = true
postcard.workspace = true

[dev-dependencies]
tempfile.workspace = true
